
stages:
  - test

test:windows:
  stage: test
  tags:
    - windows
  script:
    - scripts/ci.sh

test:darwin:
  stage: test
  tags:
    - darwin
  script:
    - scripts/ci.sh

test:linux:
  stage: test
  tags:
    - linux
  script:
    - scripts/ci.sh
